[package]
name = "web_embed"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
actix-web = "4.10.2"
clap = { version = "4.5.37", features = ["cargo"] }
mime_guess = "2.0.5"
rust-embed = "8.7.1"
